config/routes.rb
Rails.application.routes.draw do
  get 'task/Tasks'

  root 'welcome#index'
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :item, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def create
      @task = Task.new(task_params)
      if @task.save
        flash[:notice] = 'Item has been added'

        redirect_to root_path
      else
        flash[:alert] = "Text field cannot be blank"
        redirect_to root_path
      end
    end
  def destroy
      @task = Task.find(params[:id])
      @task.destroy
      flash[:notice] = 'Item has been removed'
      redirect_to root_path
  
  end
    private 
      def task_params
        params.require(:task).permit(:item)
      end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @tasks = Task.all
  end
end

app/helpers/additional_helper.rb
module AdditionalHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
     
    
    </div>
  </body>
</html>

app/views/task/Tasks.html.erb
<h1>Task#Tasks</h1>
<p>Find me in app/views/task/Tasks.html.erb</p>

app/views/welcome/index.html.erb
<h1>To Do List</h1>

<div class='top'>
    <h2>Enter a task here</h2>
    <%= form_with scope: :task, url: tasks_path do |f| %>
        <br>
        <%= f.text_field :item, placeholder: "example: Go Shopping" %>
        <br><br>
        <%= f.submit "Enter", class: "btn btn-primary" %>
    <% end %> 
</div>
<div class='bottom'>
    
    <h2> Your List</h2>
    <hr>
    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
    <% end %>
    <ol>
    <% @tasks.each do |task| %>
        <h3>
            <li>
                <%=task.item %>
                <span class='delete-button'><%= link_to 'remove', task, method: :delete, data: {confirm: "Would you like to delete this item?"} %></span>
            </li>
                
        </h3>
    <% end %>
    </ol>
</div>